# Generated by Django 5.1.7 on 2025-03-08 18:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elibrary", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="borrowing",
            name="due_date",
        ),
        migrations.AddField(
            model_name="borrowing",
            name="return_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="rating",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ebook",
            name="genre",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="elibrary.genre",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ebook",
            name="licenses",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="rating",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
