# Generated by Django 5.1.7 on 2025-03-08 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("elibrary", "0003_borrowing_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="borrowing",
            name="due_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 3, 8, 18, 40, 58, 867656, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
